### ISSUE TITLE
Page refresh on Radio page doesn't always work

### ISSUE THREAD

**Issue by nanometrenat** [servalproject/lbard#6] opened 2017-11-17 11:19 UTC
http://192.168.3.1:21506/

This page should completely refresh every couple of seconds or so - but we have found in the last few days that sometimes the same information is shown even after a page refresh.  Need to ensure the current information is always shown.

Suspect related to time going backwards (e.g. see #5 )

**Comment by gardners** [comment] 2018-04-24 05:07
A number of probable causes to this have been fixed, and the page now contains instrumentation to make it easier to see when it it does happen.  In use in the lab with the latest firmware, the problem is no longer occurring, so closing issue. Will reopen if the problem returns.

**Closed by gardners** 2018-04-24 05:07 UTC
